/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Login;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author Laura Sabillon
 */
public class Log_in extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Log_in() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem6 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        enter = new javax.swing.JButton();
        contraseña = new javax.swing.JPasswordField();
        mostrar = new javax.swing.JCheckBox();
        login_square = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        login_square1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("jCheckBoxMenuItem5");

        jCheckBoxMenuItem6.setSelected(true);
        jCheckBoxMenuItem6.setText("jCheckBoxMenuItem6");

        setBackground(new java.awt.Color(0, 0, 51));
        setMaximumSize(new java.awt.Dimension(1660, 1080));
        setMinimumSize(new java.awt.Dimension(1660, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("LOGIN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Usuario: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/blue_button.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, 50));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Contraseña: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, 30));

        usuario.setBackground(new java.awt.Color(8, 8, 29));
        usuario.setForeground(new java.awt.Color(204, 204, 204));
        usuario.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(119, 83, 2), null));
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 210, 30));

        exit.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(153, 153, 153));
        exit.setText("EXIT");
        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 190, 60));

        enter.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        enter.setForeground(new java.awt.Color(153, 153, 153));
        enter.setText("LOGIN");
        enter.setBorderPainted(false);
        enter.setContentAreaFilled(false);
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 190, 50));

        contraseña.setBackground(new java.awt.Color(8, 8, 29));
        contraseña.setForeground(new java.awt.Color(204, 204, 204));
        contraseña.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(119, 83, 2), null));
        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });
        contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contraseñaKeyPressed(evt);
            }
        });
        add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 210, 30));

        mostrar.setBackground(new java.awt.Color(0, 0, 51));
        mostrar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        mostrar.setForeground(new java.awt.Color(153, 153, 153));
        mostrar.setText("Mostrar Contraseña");
        mostrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 160, 40));

        login_square.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/blue_button_out.jpg"))); // NOI18N
        login_square.setText("jLabel4");
        add(login_square, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 370, 100));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/blue_button.jpg"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/blue_button.jpg"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 190, 60));

        login_square1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/blue_button_out.jpg"))); // NOI18N
        login_square1.setText("jLabel4");
        add(login_square1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 630, 370, 100));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/blue_button.jpg"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/daaark_out.jpg"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(119, 83, 2), null));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 510, 590));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/cheess_out.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1690, 910));
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
        if (usuario.getText().equals("") && contraseña.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Favor ingresar el usuario y contraseña. ");
        }
        else if (usuario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Favor ingresar un usuario. ");
        }else if (contraseña.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Porfavor ingresar una contraseña.");
        }else{
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecto.","Message",JOptionPane.ERROR_MESSAGE);
        }                 
    }//GEN-LAST:event_enterActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        // TODO add your handling code here:
        if (mostrar.isSelected()){
            contraseña.setEchoChar((char)0);
    }
        else{
            contraseña.setEchoChar('*');
        }        
    }//GEN-LAST:event_mostrarActionPerformed

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        // TODO add your handling code here:}       
    }//GEN-LAST:event_contraseñaActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usuarioActionPerformed

    private void contraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseñaKeyPressed
        // TODO add your handling code here:
        String password = contraseña.getText();
        int longitud = password.length();
        char caracteres = evt.getKeyChar();
        if (longitud<5){
            contraseña.setEditable(true);
        }else if (longitud==5){
            contraseña.setEditable(false);
        }
    if( evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE){
        contraseña.setEditable(true);
    }
      
    }//GEN-LAST:event_contraseñaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JButton enter;
    private javax.swing.JButton exit;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel login_square;
    private javax.swing.JLabel login_square1;
    private javax.swing.JCheckBox mostrar;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
