/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;
/**
 *
 * @author Laura Sabillon
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jugador = new javax.swing.JButton();
        salida = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jugador.setFont(new java.awt.Font("Georgia", 1, 21)); // NOI18N
        jugador.setForeground(new java.awt.Color(153, 153, 153));
        jugador.setText("Crear Player");
        jugador.setBorder(null);
        jugador.setBorderPainted(false);
        jugador.setContentAreaFilled(false);
        jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugadorActionPerformed(evt);
            }
        });
        getContentPane().add(jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 190, 60));

        salida.setFont(new java.awt.Font("Georgia", 1, 21)); // NOI18N
        salida.setForeground(new java.awt.Color(153, 153, 153));
        salida.setText("EXIT");
        salida.setBorder(null);
        salida.setBorderPainted(false);
        salida.setContentAreaFilled(false);
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });
        getContentPane().add(salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 190, 60));

        Login.setFont(new java.awt.Font("Georgia", 1, 21)); // NOI18N
        Login.setForeground(new java.awt.Color(153, 153, 153));
        Login.setText("Login");
        Login.setBorder(null);
        Login.setBorderPainted(false);
        Login.setContentAreaFilled(false);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 190, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/extra button.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 190, 60));

        jLabel1.setFont(new java.awt.Font("Colonna MT", 1, 58)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(96, 0, 0));
        jLabel1.setText("Vampire Wargame");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 580, 70));

        jLabel3.setFont(new java.awt.Font("Colonna MT", 1, 72)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(210, 195, 195));
        jLabel3.setText("Castlevania: Lord of  Shadows");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 990, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/extra button.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 190, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/extra button.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 190, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Vampire_Wargame.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -260, 1560, 1070));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
    Log_in login = new Log_in();
    
    // Remove all existing components from the content pane
    getContentPane().removeAll();
    
    // Set the layout of the content pane to null
    getContentPane().setLayout(null);
    
    // Set the bounds of the JPanel
    login.setBounds(0, 0, getWidth(), getHeight());
    
    // Add the JPanel to the content pane
    getContentPane().add(login);
    
    // Refresh the content pane to reflect the changes
    getContentPane().revalidate();
    getContentPane().repaint();                                                                                                                   
    }//GEN-LAST:event_LoginActionPerformed

    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salidaActionPerformed

    private void jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugadorActionPerformed
        // TODO add your handling code here:
    Registro registro = new Registro();
    
    // Remove all existing components from the content pane
    getContentPane().removeAll();
    
    // Set the layout of the content pane to null
    getContentPane().setLayout(null);
    
    // Set the bounds of the JPanel
    registro.setBounds(0, 0, getWidth(), getHeight());
    
    // Add the JPanel to the content pane
    getContentPane().add(registro);
    
    // Refresh the content pane to reflect the changes
    getContentPane().revalidate();
    getContentPane().repaint();   
    }//GEN-LAST:event_jugadorActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jugador;
    private javax.swing.JButton salida;
    // End of variables declaration//GEN-END:variables
}
