/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Login;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;
import javax.swing.JOptionPane;
/**
 *
 * @author Laura Sabillon
 */
public class Registro extends javax.swing.JPanel {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        crear = new javax.swing.JButton();
        end = new javax.swing.JButton();
        mostrar = new javax.swing.JCheckBox();
        confirmacion = new javax.swing.JPasswordField();
        contraseña = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("CREAR  PLAYER");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 218, 41));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Ingresar Usuario: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, 50));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Ingresar Contraseña");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, 50));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Confirmar Contraseña");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, 30));

        usuario.setBackground(new java.awt.Color(51, 0, 0));
        usuario.setForeground(new java.awt.Color(204, 204, 204));
        usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 240, 30));

        crear.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        crear.setForeground(new java.awt.Color(153, 153, 153));
        crear.setText("CREAR\n");
        crear.setBorder(null);
        crear.setBorderPainted(false);
        crear.setContentAreaFilled(false);
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        add(crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 190, 50));

        end.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        end.setForeground(new java.awt.Color(153, 153, 153));
        end.setText("EXIT\n");
        end.setBorder(null);
        end.setContentAreaFilled(false);
        end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endActionPerformed(evt);
            }
        });
        add(end, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, 190, 48));

        mostrar.setBackground(new java.awt.Color(51, 0, 0));
        mostrar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        mostrar.setForeground(new java.awt.Color(153, 153, 153));
        mostrar.setText("Mostrar Contraseña");
        mostrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, 160, 40));

        confirmacion.setBackground(new java.awt.Color(51, 0, 0));
        confirmacion.setForeground(new java.awt.Color(153, 153, 153));
        confirmacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmacionActionPerformed(evt);
            }
        });
        confirmacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmacionKeyPressed(evt);
            }
        });
        add(confirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, 240, 30));

        contraseña.setBackground(new java.awt.Color(51, 0, 0));
        contraseña.setForeground(new java.awt.Color(153, 153, 153));
        contraseña.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contraseñaKeyPressed(evt);
            }
        });
        add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 240, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/extra button.jpg"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, 70));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/extra button.jpg"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, 70));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/extra button.jpg"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, -1, 70));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/extra button.jpg"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, -1, 70));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/extra button.jpg"))); // NOI18N
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/extra buttonr+.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 270, 80));

        jLabel7.setBackground(new java.awt.Color(102, 0, 0));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, 120));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/doooor.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -210, 1590, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
        String username = usuario.getText();
    }//GEN-LAST:event_usuarioActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        // TODO add your handling code here:
    if (usuario.getText().equals("") && contraseña.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Favor ingresar usuario y contraseña.");
    }
    else if (usuario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Favor ingresar un usuario. ");
    }
    else if (contraseña.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Porfavor ingresar una contraseña.");
        }
    else if(!confirmacion.getText().equals(contraseña.getText())){
        JOptionPane.showMessageDialog(null, "Contraseña no coincide.","Message",JOptionPane.ERROR_MESSAGE);
    }
    else{
        
    }
    }//GEN-LAST:event_crearActionPerformed

    private void endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_endActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        // TODO add your handling code here:
        if (mostrar.isSelected()){
            contraseña.setEchoChar((char)0);
            confirmacion.setEchoChar((char)0);
    }
        else{
            confirmacion.setEchoChar('*');
            contraseña.setEchoChar('*');
        }        
    }//GEN-LAST:event_mostrarActionPerformed

    private void confirmacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmacionKeyPressed
        // TODO add your handling code here:
        String password = confirmacion.getText();
        int longitud = password.length();
        char caracteres = evt.getKeyChar();
        if (longitud<5){
            confirmacion.setEditable(true);
        }else if (longitud==5){
            confirmacion.setEditable(false);
        }
    if( evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE){
        confirmacion.setEditable(true);
    }
    }//GEN-LAST:event_confirmacionKeyPressed

    private void confirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmacionActionPerformed
        // TODO add your handling code here:
        String password = confirmacion.getText();
    }//GEN-LAST:event_confirmacionActionPerformed

    private void contraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseñaKeyPressed
        // TODO add your handling code here:
        String password = contraseña.getText();
        int longitud = password.length();
        char caracteres = evt.getKeyChar();
        if (longitud<5){
            contraseña.setEditable(true);
        }else if (longitud==5){
            contraseña.setEditable(false);
        }
    if( evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE){
        contraseña.setEditable(true);
    }        
    }//GEN-LAST:event_contraseñaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmacion;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JButton crear;
    private javax.swing.JButton end;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox mostrar;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
